// <auto-generated />
using System;
using BdoMarketTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BdoMarketTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303010238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BdoMarketTracker.Models.TrackedItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tracked_items");
                });

            modelBuilder.Entity("BdoMarketTracker.Models.TradeSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BasePrice")
                        .HasColumnType("bigint")
                        .HasColumnName("base_price");

                    b.Property<long>("CurrentStock")
                        .HasColumnType("bigint")
                        .HasColumnName("current_stock");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<long>("LastSoldPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sold_price");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("TotalPreorders")
                        .HasColumnType("bigint")
                        .HasColumnName("total_preorders");

                    b.Property<long>("TotalTrades")
                        .HasColumnType("bigint")
                        .HasColumnName("total_trades");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("trade_snapshots");
                });

            modelBuilder.Entity("BdoMarketTracker.Models.TradeSnapshot", b =>
                {
                    b.HasOne("BdoMarketTracker.Models.TrackedItem", "Item")
                        .WithMany("Snapshots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BdoMarketTracker.Models.TrackedItem", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
